---
title: "Surprise - They're Different!"
subtitle: "Comparing Frequentist and Bayesian Approaches in Public Policy"
author:
  - name: Stefani Langehennig, PhD 
    orcid: 0000-0002-0897-6556
    email: stefani.langehennig@du.edu
    affiliation: University of Denver
  - name: Zach del Rosario, PhD
    orcid: 0000-0003-4676-1692
    email: zdelrosario@olin.edu
    affiliation: Olin College of Engineering
  - name: Mine Dogucu, PhD
    orcid: 0000-0002-8007-934X
    email: mdogucu@uci.edu
    affiliation: University of California Irvine
abstract: |
  Implementing quantitative methodological techniques is a crucial piece of understanding public policy. While quasi-experimental, spatial (diffusion), and mixed methods are most commonly used when teaching policy studies, little research exists on using Bayesian approaches for policy learning, or how the outcomes from traditional quantitative approaches differ from a Bayesian approach. We propose an applied learning activity for students of public policy that exposes them to Bayesian methods and explores the differences between this statistical paradigm and more commonly used approaches. We do this using a structured interrogation of the [The Climate and Economic Justice Screening Tool](https://screeningtool.geoplatform.gov/en/) (CEJST) and the epistemological framings in the 5E model [@elby2010epistemological]. The activity illustrates the importance of statistical assumptions, and by extension, the impact that different quantitative methods have on understanding public policy. The goal of the study is to introduce students, instructors, and practitioners of public policy to a new way of using statistics, equipping them with the tool set and logical processes necessary to apply either approach as they see fit when studying public policy.
keywords:
  - Active Learning
  - Public Policy
  - Bayesian Statistics
  - Undergraduate Education
number-sections: true
bibliography: bibliography.bib
geometry: margin=1in 
#mainfont: Calibri
fontsize: 12pt
---

## Introduction
[motivation, justification of research, roadmap of paper]

The study and implementation of public policy relies on a variety of methodologies, primarily because they are concerned with understanding both the application, practice, and impacts of those policies. While a variety of methodologies, both quantitative and qualitative, are used to understand policy, largely overlooked is the implementation of Bayesian techniques in policy learnings. 

[paradigm shift among practitioners in the need for evidence-based decision-making that relies on quant methods]


Traditional quantitative methods of public policy usually...

## Background
[what's been done/current state of literature, what we're adding, why it's important - some literature argues quantitative methods may not still be prevalent (see @morccol2010methods)]


- broader discussion on teaching quantitative methods across different disciplines/cross-disciplinary approaches to quantitative methodology education
  - 
- note the different methods and approached traditional used to quantitatively study public policy
  - this can include (but is not limited to):
- also note the stats learning literature and where we situate epistemological framings



## Applied Activity: Comparing Frequentist & Bayesian Approaches
We designed, implemented, and evaluated an activity that highlights the differences between Frequentist and Bayesian statistics. Our primary work included designing an activity that takes students through a structured interrogation of a dataset, with the pilot launching during spring of 2024. Aspirationally, we evaluated this activity’s impact on students’ statistical knowledge and epistemological framings [@elby2010epistemological], discussed more below.

The activity is focused on a real dataset - [The Climate and Economic Justice Screening Tool](https://screeningtool.geoplatform.gov/en/) (CEJST) - to which groups of students are given guided statistical analysis. Students follow a structured process to analyze the dataset and interpret their results. However, we give different groups different versions of the activity: some will receive a Frequentist approach, while the others will receive a Bayesian approach. By carefully engineering the analyses to reach different conclusions, we aim to surprise students with diverging conclusions. Through a final full-group discussion, we highlight the importance of statistical assumptions, completing the comparison of Frequentist and Bayesian approaches.

#### Recruitment
The activity is designed for use in a classroom for non-statistics majors. To pilot the activity among students before disseminating widely, we recruited from two distinct populations at our respective institutions. Students recruited from the University of Denver Daniels College of Business have various majors ranging from Business Information and Analytics to Marketing, while students recruited from Olin College of Engineering have focus on a variety of engineering-related topics. 

For both institutions, participants had to be at least 18 years of age or older and must have completed at least one entry-level statistics course. At the University of Denver, all students enrolled in a business school major must complete three courses that are part of their statistics sequence (INFO 1010, 1020, and 2020). Students who were currently enrolled in the Winter 2024 quarter of INFO 1020 received a Canvas announcement about the opportunity to participate in a research study involving an applied activity about statistical inference outside of normal class hours. XX students volunteered to participate after receiving the Canvas announcement. These students met with Dr. Langehennig and completed the activity over the course of approximately 120 minutes and received pizza at the end of the activity. 

[paragraph here on Olin recruitment]

#### Activity Materials

Materials for the activity are openly available on our [GitHub repository](https://github.com/bayes-bats/tier2-freq-bayes) for instructors to use. Important starter documents include the [run of show](https://github.com/bayes-bats/tier2-freq-bayes/blob/main/development/run-of-show.md), which outlines at a high level the different steps of the activity, as well as the artifacts used in the activity. Further, the learning objectives and details of the activity are fleshed out in the [introduction document](https://github.com/bayes-bats/tier2-freq-bayes/blob/main/development/01-introduction-main.qmd). Finally, instructors can watch a [video overview](https://www.youtube.com/watch?v=dwNLcFqQqnE) of the activity on YouTube as well. 

#### Activty Steps


## Evaluation
In addition to exposing students to different statistical paradigms, we are interested in students' awareness of Bayesian methods and their _epistemological framings_—their assumptions about the nature and accessibility of "truth" [@elby2010epistemological]. Using pre- and post-pre-activity surveys, we measure students’ self-reported familiarity of fundamental Bayesian ideas. Specifically, we measure their attitudes before the activity, as well as their change in attitudes after the activity, with respect to ideas around statistical inference. The reason for using a post-pre design after the activity is straightforward. The idea is to capture changes in self-perceived attitudes about a topic by asking participants to consider where they think they were before the activity, followed by where they think they are now (see @hiebert2014power). The participants give themselves two ratings to capture this before and after reflection, as shown below.


## Conclusion

[overview of findings from evaluation (surveys) here]

This activity bridges the gap between the common Frequentist approach oft taught in both undergraduate and graduate statistics classes and the Bayesian paradigm, to which many students have not been exposed. We do this using an applied approach, with an eye towards answering education research questions. While many teaching methods highlight the theoretical similarities and differences between frequentists and Bayesians, our activity moves beyond by grounding the comparison in a real-data application, as well as measuring the impact of applying both frameworks in the classroom. In doing so, we hope to introduce students to a new way of using statistics, equipping them with the tool set and logical processes necessary to apply either the frequentist or Bayesian (or both) approaches as they see fit.

Our activity uses an active learning approach, rather than passive lecture. Active learning has been shown to result in superior learning outcomes for students, particularly those from underrepresented groups [@freeman2014active]. In this way, our proposed activity will promote broader impacts of Bayesian thinking.

Our more speculative research goal—to promote more nuanced epistemological framings among students—has further potential impacts. @elby2010epistemological argue that a "sophisticated" personal epistemology is actually achieved when one has access to multiple epistemological framings and can choose to switch between them based on what is productive for the context at hand. Students who can recognize and critique the assumptions underpinning their analyses (treating them as tentative), but carry out their analyses respecting those analyses (treating them as true) will likely be more effective as practicing statisticians. Getting students to recognize the importance of assumptions—and to practice adopting different assumptions—will be a critical first step in developing these multiple epistemological framings.



