  ---
title: "Introduction to Different Statistical Paradigms"
subtitle: "Comparing Frequentist and Bayesian Approaches"
format: html
author: 
  - name: Stefani Langehennig
  - name: Zach del Rosario
---

## Introduction

This activity is all about *statistical inference* and *statistical assumptions*. Both are important when you have data and want to use that data to help you better understand some phenomenon about the world. For example, in our [Context Reference Guide](https://github.com/bayes-bats/tier2-freq-bayes/blob/main/development/00-context-main.qmd) using the CEJST dataset, we used data to understand general trends around sustainability and disadvantaged communities. However, at this point, we have not crafted specific research questions or hypotheses that we would like to rigorously test with the data we have. Nor do we know, with any degree of certainty, how "correct" the trends are that we saw in our data or all the ways that this trend could have occurred. 

There are a few different ways that we can test our hypotheses using methods of statistical inference. Statistical inference allows us to take some data, create a model, and make sense of the complex world around us. Each method has a set of assumptions built into it, which influences the approach you take to answer your research questions, as well as the way you interpret your findings. In the activity that follows, you will have the opportunity to use methods of statistical inference to answer a research question and explain, based on the set of assumpted baked into your approach, your ultimate findings. 

## Learning Objectives

By the end of the activity, you should be able to:

1. Evaluate multiple hypotheses using inferential statistical results
2. Connect your evaluation of hypotheses with real-world factors
3. State the primary statistical assumptions for Frequentist and Bayesian inference, and understand how they can lead to different conclusions

 
<!-- solution-begin  -->

By the end of the activity, you should be able to:

1. Evaluate multiple hypotheses using inferential statistical results.
  - The hypotheses we consider in this activity concern patterns of inequality: Do Black Americans experience a disproportionate level of energy expenditure?
  - The inference we consider is across U.S. States: Do patterns of inequality persist across states? What do we conclude when we have limited data?
2. Connect your evaluation of hypotheses with real-world factors.
  - We ask students to think critically about *why* patterns of inequality do---or do not---appear in different states. E.g., what is different about policy in Colorado vs Florida?
3. State the primary statistical assumptions for Frequentist and Bayesian inference, and understand how they can lead to different conclusions.
  - We will focus on the inclusion of a prior and its interaction with small/large sample size. A prior is particularly useful when we have limited data. The prior becomes less important when we have a large dataset.

<!-- solution-end  -->

## Before We Begin...

Ask yourself the following questions:

::: {.callout-note icon=false title="Warmup Questions"}
- What do you remember about analyzing a dataset with statistics?
- What do you know about frequentist and Bayesian statistics? (*Note*: It's okay if you don't know what this means!)
:::

Discuss these questions with the people at your table.

## The Big Idea: Inference

Statistical inference is drawing conclusions about **data we haven't seen** using **only the data that are available.** As a simple example, if we're interested in the energy burden pattern in Colorado but we only have data from Massachusetts, we should be careful when trying to use the MA data to predict patterns in CO. Crucially, **the assumptions we make for inference will strongly affect the conclusions we make.** 

::: {.callout-note icon=false title="All models are wrong...."}
All statistical analyses involve making assumptions---we'll practice making and assessing statistical assumptions in this activity.
:::

## Crafting Research Questions & Hypotheses

Ahead of using data and statistical inference, we usually create theory-based _research questions_ and _hypotheses_ that help guide what we expect to find. Both are focused on an aspect of the world that we want to know more about. However, research questions tend to be open-ended, allowing for discussion on what the outcome might be and what might explain it. For example, a research question about sustainability and diverse communities may look like this:
  
  > _Why does the projected flood risk vary among different communities in U.S. Census tracts?_
    
Hypotheses, on the other hand, tend to be closed-ended, articulating a certain relationship between an outcome and the things that influence that outcome. For example, one of the testable hypotheses stemming from the research question on projected flood risk may be:

  > _As the population density of Hispanic communities increases (decreases), the projected flood risk increases (decreases)._
  
Note that this hypothesis is succinct and testable with the data we have. It is also directly related to our more general research question. 

## Paradigms in Statistical Inference

There are a few different ways to draw conclusions about questions we have using data. We will focus on two inferential perspectives in this class: _Frequentist_ and _Bayesian_. Let's discuss the critical differences between the two paradigms with the [Critical Differences Reference Guide](https://github.com/bayes-bats/tier2-freq-bayes/blob/main/development/03-one-pager-main.qmd).

::: {.callout-note icon=false title="Frequentist & Bayesian Statistical Inference"}
How are Frequentist and Bayesian approaches similar? How are they different?
:::

## Next Steps

Given the context we have on sustainability trends among disadvantaged communities using just a few of the variables in the CEJST dataset, we can develop a research question and hypotheses to test using methods of statistical inference:

__Research Question:__ 

  > _Do Black Americans experience a disproportionate level of energy expenditure?_

__Hypothesis:__

  > _As the population of Black Americans increases (decreases), the level of energy expenditure increases (decreases)._


Next, we are going to test our hypothesis and answer our research question using the CEJST dataset. We will compare and discuss the results of our analyses using Frequentist and Bayesian methods to see if they align with our expectations based on the approach we took and assumptions we made. 


