---
title: "Activity Wrap-Up"
subtitle: "Comparing Frequentist and Bayesian Approaches"
format: html
author: 
  - name: Stefani Langehennig
  - name: Zach del Rosario
---


## Overview

In this activity, we learned more about *statistical inference* and *statistical assumptions* through the lenses of Frequentists and Bayesians. We used the [CEJST dataset](https://screeningtool.geoplatform.gov/en/) to understand general trends around sustainability and disadvantaged communities, as well as crafted specific research questions or hypotheses that we would like to rigorously test with the data we have. Our research question asked:

  | _Do Black Americans experience a disproportionate level of energy expenditure?_

And our primary hypothesis we wanted to answer is:

  | _As the population of Black Americans increases (decreases), the level of energy expenditure increases (decreases)._
  
To test this, we focused on the Energy Burden Percentile as our dependent variable and Percent Black Census Tract as our primary independent variable in our models. We examined some descriptive statistics to get a better sense of the trends in our data and to help us better understand the relationship between these two variables. 

Our initial data exploration found that there is a clear positive trend between the population of Black Americans and the level of energy burden in their respective Census tract for Florida and Massachusetts. However, Colorado has a negative trend, which is somewhat surprising given the results of the other two states. The results from our exploratory analysis suggests there are inequitable outcomes between the states.

Based on these preliminary trends, we used statistical inference to answer our questions. Some students received an analysis completed in the Frequentist framework, while some students received an analysis completed in the Bayesian framework. 

::: {.callout-note icon=false title="Questions for the Class"}
- Did you find support for or against our hypothesis?
- How would you answer our research question now that we have analyzed the data?
- What can we conclude about the relationship between sustainability and disadvantaged communities? What might you recommend from a policy-making perspective?
:::

---

## Differences between Frequentist & Bayeisan Approaches

There are key differences between Frequentist and Bayesian approaches. In the activity, we focused on model summaries and general inference.

**General Inference**

For general inference, we are concerned with answering questions about a _larger_ dataset, while only having access to a _smaller_ dataset.

1. Translate our question into a mathematical model*
2. Fit the model using data
3. Interpret model results in terms of our question


| Frequentist | Bayesian | 
|-------------|----------|
| Provides: Pr(data $|$ hypothesis) | Provides: Pr(hypothesis $|$ data) |
| Decision based on hard cut-off | Decision based on posterior distribution |

: General Inference Comparison {.sm .bordered}

**Model Summaries**

* Statistical models are complex objects, so we use _model summaries_ to help.
* Statistical models represent the _uncertainty due to limited data_.

Some common summaries:


|Point estimate | Uncertainty | Interval|
|---------------|-------------|---------|
|42             |4            |(42 +/- 2x4) = (34, 50) |

: Common Model Summaries {.sm .bordered}


Here are the differences in how Frequentists and Bayesians get model summaries:


| Frequentist | Bayesian | 
|-------------|----------|
| Maximum likelihood estimate | Maximum of the posterior density |
| Standard error | Posterior standard deviation |
| Confidence interval | Credible interval |

: Model Summary Comparison {.sm .bordered}

---

### Applying the Differences

With the remainder of class time, separate into groups of 2-3 people, where each group should have at least 1 person who did the Frequentist analysis and 1 person who did the Bayesian analysis. Using the [Critical Differences Reference Guide](https://github.com/bayes-bats/tier2-freq-bayes/blob/main/development/03-one-pager-main.qmd), discuss the following:

- How do our modeling choices affect our outcomes of interest based on the assumptions we know about both approaches? Are the results for our hypothesis different? If so, how?
- How do we interpret the coefficients ($\beta_0$ and $\beta_1$) in both the Frequentist and Bayesian models?
- How might we improve our model based on what we know from our **model summaries** and **general inference** for both approaches?

Jot down 2-3 sentences for each question, as well as any remaining questions or concerns you have about conducting your analyses using one of the two approaches.

$*$ Requires assumptions!

---

<!-- solution-begin  -->

- Note: Reference for conceptual discussion: https://www.bayesrulesbook.com/chapter-11#ch-11-2-predictors
- At the end of the discussion, if time, have the groups share what they came up with based on their answers. 
- This should be a lively debate facilitated by the instructor; students will debate who is "correct"
- Instructor should highlight the differences between their analyses. 
  - All students started with an identical dataset and framing questions; it is the difference in their starting assumptions (i.e., a frequentist or Bayesian approach) that results in different conclusions.
  - Takeaway point: controversy isn't resolved, however statistical results are conditional on the assumptions chosen for the analysis and implies that choosing appropriate assumptions is critical to a sound analysis

<!-- solution-end  -->

