---
title: "CEJS Activity"
format: html
---



```{r setup}
#| include: false
#| echo: false
library(tidyverse)
library(rstanarm)
library(bayesplot)
library(broom.mixed)

filename <- "../data/1.0-communities.csv"
```



```{r wrangling}
#| include: false
#| echo: false
df_raw <- read_csv(filename)
df_data <- 
  df_raw %>%
  janitor::clean_names()
```

# Overview

```{r}
df_data %>% 
  filter(state_territory %in% c("Florida", "Massachusetts", "Colorado")) %>% 
  
  ggplot(aes(
    percent_black_or_african_american_alone,
    energy_burden_percentile
  )) +
  geom_point(size = 0.1) +
  geom_smooth(method = "lm") +
  geom_smooth(
    data = df_data %>% 
      select(-state_territory),
    linetype = "dotted",
    method = "lm"
  ) +
  facet_wrap(~state_territory, ncol = 2) +
  theme_minimal() +
  labs(
    x = "Percent Black",
    y = "Energy Burden Percentile",
  )
```

- Colorado has a negative trend, but this is borderline (confidence band admits a flat line)
- Wyoming has a negative trend, but this might be due to a single outlier


```{r fig1}
#| warning: false
#| echo: false
#| fig-align: center
#| fig-height: 4

```

